#!/usr/bin/env bash



## launch wofi with alt config

CONFIG="$HOME/.config/hypr/rofi/config"
STYLE="$HOME/.config/hypr/rofi/style.css"
COLORS="$HOME/.config/hypr/rofi/colors"

if [[ ! `pidof wofi` ]]; then
	rofi --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE} --color ${COLORS}
else
	pkill rofi
fi
