# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.31.3"
catpuccin = "1.7.0"
"rocks-git.nvim" = "1.5.1"
"rainbow-delimiters.nvim" = "0.4.0"
"indent-blankline.nvim" = "3.6.2"
"lualine.nvim" = "scm"
alpha-nvim = "scm"
stcursorword = {git = "sontungexpt/stcursorword"}
"deadcolumn.nvim" = "1.0.0"
nvim-notify = "3.13.5"
goto-preview = "scm"
auto-session = "2.1.0"
"hardtime.nvim" = "scm"
vim-sandwich = {git = "machakann/vim-sandwich"}
vim-easy-align = {git = "junegunn/vim-easy-align"}
cheatsheet = {git = "doctorfree/cheatsheet.nvim"}
luasnip = "2.3.0"
"comment.nvim" = "0.8.0"
"oil.nvim" = "2.9.0"
"telescope.nvim" = "scm"
"rocks-config.nvim" = "2.0.0"
nvim-lspconfig = "0.1.8"
nvim-cmp = "0.0.1"
cmp-nvim-lsp = "scm"
cmp-nvim-lsp-signature-help = {git = 'hrsh7th/cmp-nvim-lsp-signature-help'}
cmp-buffer = "scm"
cmp-path = "scm"
cmp-git = "scm"
cmp-cmdline = "scm"
cmp_luasnip = "scm"
cmp-spell = {git = 'f3fora/cmp-spell'}
cmp-ai = {git = 'jackruder/cmp-ai'}
cmp-vimtex = {git = 'micangl/cmp-vimtex'}
cmp-rpncalc = {git = 'PhilRunninger/cmp-rpncalc'}
neorg = "8.7.1"
"image.nvim" = "1.3.0"
"otter.nvim" = "1.15.1"
"nabla.nvim" = "scm"

[plugins.vimtex]
git = "lervag/vimtex"
rev = "v2.9"

[plugins."tiny-devicons-auto-colors.nvim"]
git = "rachartier/tiny-devicons-auto-colors.nvim"

[plugins.nvim-treesitter]
git = "jackruder/nvim-treesitter"
rev = "v0.9.2^{}"

[plugins.molten-nvim]
git = "benlubas/molten-nvim"
rev = "v1.8.3"

[plugins."jupytext.nvim"]
git = "GCBallesteros/jupytext.nvim"

[plugins.vim-fugitive]
git = "tpope/vim-fugitive"
rev = "v3.7^{}"

[bundles.lsp]
items = [            
    "nvim-treesitter",
    "nvim-lspconfig" ,
    "nvim-cmp"       ,
    "cmp-nvim-lsp"   ,
    "cmp-nvim-lsp-signature-help",
    "cmp-buffer"     ,
    "cmp-path"       ,
    "cmp-git"        ,
    "cmp-cmdline"    ,
    "cmp_luasnip"    ,
    "cmp-spell"      ,
    "cmp-ai"         ,
    "cmp-vimtex"     ,
    "cmp-rpncalc"    ,
]

[bundles.visuals]
items = [
    "stcursorword",
    "deadcolumn.nvim",
    "catpuccin",
    "tiny-devicons-auto-colors.nvim",
    "rainbow-delimiters.nvim",
    "lualine.nvim",
    "alpha-nvim",
    "nvim-notify",
]

[bundles.notebooktools]
items = [
    "otter.nvim",
    "molten-nvim",
    "nabla.nvim",
    "jupytext.nvim",
]


[treesitter]
# auto_highlight = "all"
# NOTE: These are parsers, not filetypes.
auto_highlight = [
    "rust",
    "python",
    "lua",
    "c",
    "r",
    "cpp",
    "java",
    "julia",
    "fortran",
    "cmake",
    "html",
    "yaml",
    "javascript",
    "css",
    "json",
    "fish",
    "bash",
    "bibtex",
    "vim",
    "vimdoc",
    "gitignore",
    "gitcommit",
    "norg",
    ]
    auto_install = "prompt" # true | false

    [treesitter.parser_map]
# You can add custom filetype to parser mappings.
# Determine the filetype with ':lua =vim.bo[0].filetype'.
# NOTE: You don't actually have to add these examples.
# They are added by default.
    PKGBUILD = "bash"
    cls = "latex"
    sty = "latex"
