# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.36.1"
catpuccin = "1.7.0"
"rocks-git.nvim" = "2.0.1"
"rainbow-delimiters.nvim" = "0.4.0"
"indent-blankline.nvim" = "3.7.1"
"lualine.nvim" = "scm"
alpha-nvim = "scm"
"deadcolumn.nvim" = "1.0.0"
nvim-notify = "3.13.5"
goto-preview = "scm"
auto-session = "2.1.0"
"hardtime.nvim" = "scm"
luasnip = "2.3.0"
"comment.nvim" = "0.8.0"
"oil.nvim" = "2.11.0"
"telescope.nvim" = "scm"
"rocks-config.nvim" = "2.1.4"
nvim-lspconfig = "0.1.8"
nvim-cmp = "scm"
cmp-nvim-lsp = "scm"
cmp-buffer = "scm"
cmp-path = "scm"
cmp-git = "scm"
cmp-cmdline = "scm"
cmp_luasnip = "scm"
neorg = "9.1.1"
"image.nvim" = "1.3.0"
"otter.nvim" = "2.3.0"
"nabla.nvim" = "scm"
nvim-treesitter= "scm"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.29.0"
tree-sitter-bash = "0.0.2"
tree-sitter-yaml = "0.0.2"
tree-sitter-vimdoc = "0.0.2"
tree-sitter-vim = "0.0.2"
tree-sitter-rust = "0.0.2"
tree-sitter-r = "0.0.2"
tree-sitter-python = "0.0.2"
tree-sitter-norg = "0.2.4"
tree-sitter-lua = "0.0.2"
tree-sitter-julia = "0.0.2"
tree-sitter-json = "0.0.2"
tree-sitter-javascript = "0.0.2"
tree-sitter-java = "0.0.2"
tree-sitter-html = "0.0.2"
tree-sitter-gitignore = "0.0.2"
tree-sitter-gitcommit = "0.0.2"
tree-sitter-fortran = "0.0.2"
tree-sitter-fish = "0.0.2"
tree-sitter-css = "0.0.2"
tree-sitter-cpp = "0.0.3"
tree-sitter-cmake = "0.0.2"
tree-sitter-c = "0.0.3"
tree-sitter-toml = "0.0.2"

[plugins.stcursorword ]
git = "sontungexpt/stcursorword"
rev = "v1.0.3"

[plugins.vim-sandwich ]
git = "machakann/vim-sandwich"
rev = "v1.0.0^{}"

[plugins.vim-easy-align ]
git = "junegunn/vim-easy-align"
rev = "2.9.7^{}"

[plugins.cheatsheet ]
git = "doctorfree/cheatsheet.nvim"
rev = "8ee4d76b6f902c4017dc28eddd79d925dfc55066"

[plugins.cmp-nvim-lsp-signature-help ]
git = "hrsh7th/cmp-nvim-lsp-signature-help"
rev = "031e6ba70b0ad5eee49fd2120ff7a2e325b17fa7"

[plugins.cmp-spell ]
git = "f3fora/cmp-spell"
rev = "694a4e50809d6d645c1ea29015dad0c293f019d6"

[plugins.cmp-ai ]
git = "jackruder/cmp-ai"
rev = "45eda6f407dda136df51b5aa514e275f0827c413"

[plugins.cmp-vimtex ]
git = "micangl/cmp-vimtex"
rev = "a64b1b5eec0460144c91c4f20a45c74b8ded48ae"

[plugins.cmp-rpncalc ]
git = "PhilRunninger/cmp-rpncalc"
rev = "3d82861b41c54cb0b3c2c513563e1d8758c92625"

[plugins.vimtex]
git = "lervag/vimtex"
rev = "v2.9"

[plugins."tiny-devicons-auto-colors.nvim"]
git = "rachartier/tiny-devicons-auto-colors.nvim"
rev = "9be4af5b1bc1f26a11206ed7ce8bf44312e7941a"

[plugins.molten-nvim]
git = "benlubas/molten-nvim"
rev = "v1.8.4"

[plugins."jupytext.nvim"]
git = "GCBallesteros/jupytext.nvim"
rev = "c8baf3ad344c59b3abd461ecc17fc16ec44d0f7b"

[plugins.vim-fugitive]
git = "tpope/vim-fugitive"
rev = "v3.7^{}"

[plugins.efmls-configs-nvim]
git = "creativenull/efmls-configs-nvim"
rev = "v1.7.0"

[plugins."lsp-format.nvim"]
git = "lukas-reineke/lsp-format.nvim"
rev = "v2.6.5"

[bundles.lsp]
items = [            
    "nvim-treesitter",
    "nvim-lspconfig" ,
    "nvim-cmp"       ,
    "cmp-nvim-lsp"   ,
    "cmp-nvim-lsp-signature-help",
    "cmp-buffer"     ,
    "cmp-path"       ,
    "cmp-git"        ,
    "cmp-cmdline"    ,
    "cmp_luasnip"    ,
    "cmp-spell"      ,
    "cmp-ai"         ,
    "cmp-vimtex"     ,
    "cmp-rpncalc"    ,
    "efmls-configs-nvim",
    "lsp-format.nvim",
    "mason.nvim",
    "mason-lspconfig.nvim",
]

[bundles.visuals]
items = [
    "stcursorword",
    "deadcolumn.nvim",
    "catpuccin",
    "tiny-devicons-auto-colors.nvim",
    "rainbow-delimiters.nvim",
    "lualine.nvim",
    "alpha-nvim",
    "nvim-notify",
]

[bundles.notebooktools]
items = [
    "otter.nvim",
    "molten-nvim",
    "nabla.nvim",
    "jupytext.nvim",
]


[treesitter]
# auto_highlight = "all"
# NOTE: These are parsers, not filetypes.
auto_highlight = [
    "rust",
    "python",
    "lua",
    "c",
    "r",
    "cpp",
    "java",
    "julia",
    "fortran",
    "cmake",
    "html",
    "yaml",
    "javascript",
    "css",
    "json",
    "fish",
    "bash",
    "bibtex",
    "vim",
    "vimdoc",
    "gitignore",
    "gitcommit",
    "norg",
    ]
    auto_install = "prompt" # true | false

    [treesitter.parser_map]
# You can add custom filetype to parser mappings.
# Determine the filetype with ':lua =vim.bo[0].filetype'.
# NOTE: You don't actually have to add these examples.
# They are added by default.
    PKGBUILD = "bash"
    cls = "latex"
    sty = "latex"
